apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: queue-webchat-temp
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: dapr-redis:6379
  - name: redisPassword
    value: "q.123"
