# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: queue-email
# spec:
#   type: pubsub.rabbitmq
#   version: v1
#   metadata:
#   - name: connectionString
#     value: amqp://admin:admin@localhost:5672
#   - name: deletedWhenUnused
#     value: "false"
#   - name: deliveryMode
#     value: "0"

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: queue-email
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: dapr-redis:6379
  - name: redisPassword
    value: "q.123"
