apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: dapr_redis:36378
  - name: redisPassword
    value: "q.123"
  - name: actorStateStore
    value: "true"
